language: java
os: linux
jdk:
  - openjdk12
services:
  - docker
cache:
  directories:
    - $HOME/.m2
# skip installation step
install: true
script:
  - ./mvnw --settings .maven.xml clean package -B -Pdocker docker:push